---
- name: Install lsyncd
  yum: name=lsyncd state=present
  when: ansible_os_family == "RedHat"

- name: Ensure {{ lsyncd_watch_dir }} is present
  file: path={{ lsyncd_watch_dir}} state=directory

- name: Ensure log directory is present
  file: path={{ lsyncd_log_path }} mode=0755 owner=root group=root state=directory
