---
- name: Install lsyncd
  yum: name=lsyncd state=present
  when: ansible_os_family == "RedHat"

- name: Ensure log directory is present
  file: path={{ lsyncd_log_path }} mode=0755 owner=root group=root state=directory

- name: Configure lsyncd
  template: src=lsyncd.conf.j2 dest={{ lsyncd_conf_name }}

- name: Enable and start service
  service: name=lsyncd enabled=yes state=started
